/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TemplatesImport } from './routes/templates'
import { Route as SiteMapImport } from './routes/site-map'
import { Route as BrandsImport } from './routes/brands'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TemplatesRoute = TemplatesImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRoute,
} as any)

const SiteMapRoute = SiteMapImport.update({
  id: '/site-map',
  path: '/site-map',
  getParentRoute: () => rootRoute,
} as any)

const BrandsRoute = BrandsImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsImport
      parentRoute: typeof rootRoute
    }
    '/site-map': {
      id: '/site-map'
      path: '/site-map'
      fullPath: '/site-map'
      preLoaderRoute: typeof SiteMapImport
      parentRoute: typeof rootRoute
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/site-map': typeof SiteMapRoute
  '/templates': typeof TemplatesRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/site-map': typeof SiteMapRoute
  '/templates': typeof TemplatesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/brands': typeof BrandsRoute
  '/site-map': typeof SiteMapRoute
  '/templates': typeof TemplatesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/brands' | '/site-map' | '/templates'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/brands' | '/site-map' | '/templates'
  id: '__root__' | '/' | '/about' | '/brands' | '/site-map' | '/templates'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BrandsRoute: typeof BrandsRoute
  SiteMapRoute: typeof SiteMapRoute
  TemplatesRoute: typeof TemplatesRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BrandsRoute: BrandsRoute,
  SiteMapRoute: SiteMapRoute,
  TemplatesRoute: TemplatesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/brands",
        "/site-map",
        "/templates"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/brands": {
      "filePath": "brands.tsx"
    },
    "/site-map": {
      "filePath": "site-map.tsx"
    },
    "/templates": {
      "filePath": "templates.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
